theme: jekyll-theme-cayman
kramdown:
  coderay_tab_width: 4
  enable_coderay: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"